import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('link', { name: 'RECYCLER MA PLANCHE', exact: true }).click();
  await page.getByRole('link', { name: 'Se connecter' }).click();
  await page.getByRole('button', { name: 'S\'inscrire' }).click();
  await page.getByRole('textbox', { name: 'Nom d\'utilisateur' }).click();
  await page.getByRole('textbox', { name: 'Nom d\'utilisateur' }).fill('test');
  await page.getByRole('textbox', { name: 'Nom d\'utilisateur' }).press('Tab');
  await page.locator('#email').fill('wenafunagain@');
  await page.locator('#email').press('ArrowLeft');
  await page.locator('#email').press('ArrowLeft');
  await page.locator('#email').press('ArrowLeft');
  await page.locator('#email').press('ArrowLeft');
  await page.locator('#email').press('ArrowLeft');
  await page.locator('#email').press('ArrowLeft');
  await page.locator('#email').press('ArrowLeft');
  await page.locator('#email').press('ArrowLeft');
  await page.locator('#email').press('ArrowLeft');
  await page.locator('#email').press('ArrowLeft');
  await page.locator('#email').press('ArrowLeft');
  await page.locator('#email').press('ArrowLeft');
  await page.locator('#email').press('ArrowLeft');
  await page.locator('#email').press('ArrowLeft');
  await page.locator('#email').press('ArrowLeft');
  await page.locator('#email').press('ArrowLeft');
  await page.locator('#email').press('ArrowLeft');
  await page.locator('#email').fill('awenafunagain@');
  await page.locator('#email').press('ArrowRight');
  await page.locator('#email').press('ArrowRight');
  await page.locator('#email').press('ArrowRight');
  await page.locator('#email').press('ArrowRight');
  await page.locator('#email').press('ArrowRight');
  await page.locator('#email').press('ArrowRight');
  await page.locator('#email').press('ArrowRight');
  await page.locator('#email').press('ArrowRight');
  await page.locator('#email').press('ArrowRight');
  await page.locator('#email').press('ArrowRight');
  await page.locator('#email').press('ArrowRight');
  await page.locator('#email').press('ArrowRight');
  await page.locator('#email').press('ArrowRight');
  await page.locator('#email').press('ArrowRight');
  await page.locator('#email').press('ArrowRight');
  await page.locator('#email').press('ArrowRight');
  await page.locator('#email').press('ArrowRight');
  await page.locator('#email').fill('awenafunagain@proton.me');
  await page.locator('#email').press('Tab');
  await page.getByRole('textbox', { name: 'Mot de passe', exact: true }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Mot de passe', exact: true }).fill('I');
  await page.getByRole('textbox', { name: 'Mot de passe', exact: true }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Mot de passe', exact: true }).fill('Iloves@y');
  await page.getByRole('textbox', { name: 'Mot de passe', exact: true }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Mot de passe', exact: true }).fill('Iloves@y1000A@');
  await page.getByRole('button').first().dblclick();
  await page.getByRole('textbox', { name: 'Confirmer le mot de passe' }).click();
  await page.getByRole('textbox', { name: 'Confirmer le mot de passe' }).fill('I');
  await page.getByRole('textbox', { name: 'Confirmer le mot de passe' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Confirmer le mot de passe' }).fill('Iloves@');
  await page.getByRole('textbox', { name: 'Confirmer le mot de passe' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Confirmer le mot de passe' }).fill('Iloves@1000A@');
  await page.getByRole('button').nth(1).click();
  await page.getByRole('textbox', { name: 'Confirmer le mot de passe' }).click();
  await page.getByRole('textbox', { name: 'Confirmer le mot de passe' }).click();
  await page.getByRole('textbox', { name: 'Confirmer le mot de passe' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Confirmer le mot de passe' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Confirmer le mot de passe' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Confirmer le mot de passe' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Confirmer le mot de passe' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Confirmer le mot de passe' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Confirmer le mot de passe' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Confirmer le mot de passe' }).fill('Iloves@y1000A@');
  await page.getByRole('button', { name: 'S\'inscrire', exact: true }).click();
  await page.getByRole('button', { name: 'Se connecter' }).click();
  await page.locator('#email').click();
  await page.locator('#email').fill('awenaf');
  await page.getByRole('link', { name: 'Mot de passe oublié ?' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('awenafunagain@proton.me');
  await page.getByRole('button', { name: 'Envoyer le lien de ré' }).click();
  await page.getByRole('link', { name: 'Se connecter' }).click();
  await page.locator('#magic-email').click();
});