import { test, expect } from '@playwright/test';

test('parcours d\'achat complet avec Stripe', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await expect(page).toHaveURL('http://localhost:3000/');
  await page.getByRole('link', { name: 'CATALOGUE', exact: true }).click();
  await page.waitForURL('**/catalogue');
  await page.getByRole('button', { name: 'Type de planche' }).click();
  await page.locator('label', { hasText: 'Skate' }).click();
  await page.getByRole('button', { name: 'Prix (€)' }).click();
  await page.getByRole('slider').first().fill('13');
  await page.getByRole('slider').nth(1).fill('95');
  await page.getByRole('button', { name: 'Réinitialiser' }).click();
  const produit = page.getByRole('link', { name: /SKATE 50 €/i }).first();
  await expect(produit).toBeVisible();
  await produit.click();
  await page.getByRole('button', { name: 'Ajouter au panier' }).click();
  await page.getByRole('navigation').getByRole('link', { name: 'Panier' }).click();
  await page.waitForURL('**/panier');
  await page.getByRole('button', { name: 'Payer par carte' }).click();
  await page.getByRole('link', { name: 'Continuer en invité' }).click();
  await page.waitForURL('**/paiement/achat/livraison');
  await page.getByRole('textbox', { name: 'Prénom *' }).waitFor({ state: 'visible' });
  await page.getByRole('textbox', { name: 'Prénom *' }).fill('Luke');
  await page.getByRole('textbox', { name: 'Nom *', exact: true }).fill('Skywalker');
  await page.getByRole('textbox', { name: 'Adresse *' }).fill('32 rue des Jedi');
  await page.getByRole('textbox', { name: 'Ville *' }).fill('Mos Esleis');
  await page.getByRole('textbox', { name: 'Code postal *' }).fill('44000');
  await page.getByRole('textbox', { name: 'Email *' }).fill('luke@jedi.com');
  await page.getByRole('textbox', { name: 'Téléphone' }).fill('0987656789');
  await page.getByRole('button', { name: 'Procéder au paiement' }).click();
  await page.waitForURL('**checkout.stripe.com/**', { timeout: 60000 });
  await expect(page.locator('text=Payment method')).toBeVisible({ timeout: 20000 });
  await page.locator('iframe[name^="__privateStripeFrame"]').waitFor({ state: 'attached', timeout: 30000 });
});